name: CI
on:
  push:
    branches: [master]
    paths-ignore: ["**/*.md", "LICENSE"]
  pull_request:
    branches: [master]
    paths-ignore: ["**/*.md", "LICENSE"]
permissions:
  contents: read
jobs:
  nix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa
      - run: ./scripts/check.sh
